FROM python:3

LABEL  maintainer="jeromeaguas@gmail.com"

WORKDIR /app

COPY . /app

CMD ["python", "app.py"]
~                                                                                                                                                                       
~                                                      
